apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Dev environment — auto-sync enabled
  sourceRepos:
    - 'https://github.com/priyanshu499-ops/montra-gitops-manifests.git'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
