apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: uat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: UAT environment — manual sync, gated by team lead

  sourceRepos:
    - 'https://github.com/priyanshu499-ops/montra-gitops-manifests.git'

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: 'uat'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: true
