apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-realworld
  labels:
    app: spring-boot-realworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-boot-realworld
  template:
    metadata:
      labels:
        app: spring-boot-realworld
    spec:
      containers:
        - name: spring-boot-realworld
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
