apiVersion: v1
kind: Service
metadata:
  name: spring-boot-realworld
spec:
  type: {{ .Values.service.type }}
  selector:
    app: spring-boot-realworld
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
