nameOverride: java-app-dev
fullnameOverride: java-app-dev

global:
  replicaCount: 1
  namespace: dev

deployment:
  image:
    name: "asia-south2-docker.pkg.dev/development-498908/dev-app-images/instacard-mock-apis"
    tag: "39eca30"

  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 126Mi

  # Pull all pre-configured Spring Boot keys directly from ESO secret
  envFrom:
    - secretRef:
        name: dev-cloudsql-db-secret

  # Static overrides only (no sub-variable expansion issues)
  environment:
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
    SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"

service:
  type: ClusterIP
  specs:
    - name: http
      port: 80
      targetPort: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: java-app-dev-dev.example.com
      paths:
        - path: /
          pathType: Prefix

pdb:
  enabled: false
  minAvailable: 1

configmap:
  enabled: false
  data: {}

secret:
  enabled: false
  data: {}

networkPolicy:
  enabled: false

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70
  targetMemory: 80